### PR TITLE
Add ElasticSearch as cach storage

### PR DESCRIPTION
**Pull request by simeonackermann**
Just adds Elasticsearch as a cache backend.

### CODE REVIEW

**Comment by simeonackermann** [comment]
Sorry for the last merge

**Comment by k00ni** [comment]
Did you check, that the tests are run without errors?

**Comment by k00ni** [comment]
@simeonackermann: ping

**Comment by simeonackermann** [comment]
We need to decide about the php cache library first.

**Comment by simeonackermann** [comment]
Close this, because Nette won't be longer our cache library.

**Pull request closed without merging**
